import { Link } from "react-router-dom";
import "../index.scss";
import Menu from "@components/Menu/Menu";
import { useEffect } from "react";

export const NeuronPage = () => {
  useEffect(() => {
    window.onscroll = function () {
      myFunction();
    };

    function myFunction() {
      const winScroll =
        document.body.scrollTop || document.documentElement.scrollTop;
      const height =
        document.documentElement.scrollHeight -
        document.documentElement.clientHeight;
      const scrolled = (winScroll / height) * 100;
      document.getElementById("progressBar").style.height = scrolled + "%";
    }
  }, []);

  return (
    <div className="container mx-auto">
      <div className="grid grid-cols-1 md:grid-cols-2">
        <div style={{ textAlign: "center" }}>
          <img src="/brand-origyn.png" alt="" style={{ height: 32 }} />
          <Link to="/" className="backButton flex gap-4 mt-4">
            <img
              width={8}
              height={8}
              src="/arrow-left.svg"
              alt=""
              style={{ height: 32 }}
            />{" "}
            back to homepage
          </Link>
          <div className="progress-container">
            <div className="progress-section" />
            <div className="progress-bar" id="progressBar" />
          </div>

          {/* <img
            src="/ORIGYN_Black_Horizontal.png"
            alt=""
            style={{ margin: "40px auto", maxHeight: "60vh" }}
          /> */}
        </div>
        <div className="bg-white rounded-lg my-8 md:my-[-18px] md:rounded-none">
          <div className="flex justify-end p-8">
            <Menu />
          </div>
          <div className="flex flex-col gap-10 items-center article">
            <h2>ORIGYN Neuron</h2>
            <p>
              We are incredibly honored to announce a significant donation of{" "}
              <b>300 million OGY</b> from the <b>ORIGYN Foundation</b>. This
              generous gift, made through a dedicated neuron, will provide a
              substantial and sustainable source of funding for our ongoing and
              future projects.
            </p>
            <h3>A Generous Gift: Powering Our Future</h3>
            <p>
              <b>How it Works:</b> This neuron is in full control of the DAO and
              actively participating in the{" "}
              <a
                href="https://dashboard.internetcomputer.org/sns/leu43-oiaaa-aaaaq-aadgq-cai"
                target="_blank"
              >
                ORIGYN governance network
              </a>
              . The staking rewards generated by this neuron will be directly
              allocated to support our charitable initiatives.
            </p>
            <p>
              This innovative approach ensures a steady stream of income,
              allowing us to:
            </p>
            <p>
              <b>Scale Our Impact:</b> Expand our reach and influence by funding
              new projects and programs.
            </p>
            <p>
              <b>Foster Innovation:</b> Support cutting-edge technologies and
              innovative solutions to global challenges.
            </p>
            <p>
              <b>Sustainable funding:</b> Allow to operate for prolonged
              duration without worrying about funding sources.
            </p>
            <p>
              <b>Thank You, ORIGYN Foundation</b> We are deeply grateful to the
              ORIGYN Foundation for their visionary support. This partnership
              represents a powerful alliance between two organizations committed
              to using technology for the betterment of humanity.
            </p>
            <a
              href="https://origynfoundation.com/"
              target="_blank"
              className="button"
              style={{ width: "100%" }}
            >
              Visit ORIGYN Foundation to learn more about their mission.
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NeuronPage;
